### ISSUE TITLE
Runescape opens minimized in the corner, starts to a black screen and can only be closed by killing the Java process

### ISSUE THREAD

**Issue by annadane** [rsu-client/rsu-client#107]
Am on Debian, Jessie 8.6, Stable

@HikariKnight

**Comment by ixfd64** [comment]
I had the same issue. Try updating to OpenJDK 1.8 and see if that helps.

**Comment by ivanpu** [comment]
Looking back... it looks similar to #92.
Unless rebooting helps (I doubt it on this stage), I can suggest to try the last thing that was suggested there (and was not yet confirmed to either work or not):
Try to (re)move the `~/runescape/rsu/3rdParty/linux/cairo-nogl` directory.

**Comment by HikariKnight** [comment]
no update for over a year, closing
