### ISSUE TITLE
Incomplete loading and error

### ISSUE THREAD

**Issue by smithillusions** [rsu-client/rsu-client#111]
Hello all, @HikariKnight

Brand new linux user, so I apologize in advance for my inexperience.  I am trying to run the client on an ARM based chromebook with trusty ubuntu.  I am aware that my problem might stem from the ARM processor, but I figured I'd reach out for advice.  I installed the client as directed and ran the updater to acquire the jagexappletviewer.jar file.  When I try to run the client, it will load up to 2% then freeze along with some error text in the terminal.

Here is the output text of the 'runescape client.launch.runescape' command...

*******************************

(trusty)dan@localhost:~$ runescape client.launch.runescape
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work

WARNING: LWP::Simple module not found, API calls using LWP::Simple will either use alternative methods

RuneScape Unix Client script version 4.3.5

The script is running from a system path!
/home/dan/.config/runescape will be used as client folder instead!

Symlinking icon and updating examples
cp: "/opt/runescape/share/configs/settings.conf.example" -> "/home/dan/.config/runescape/share/configs/settings.conf.example"
cp: "/opt/runescape/share/prms/runescape.prm.example" -> "/home/dan/.config/runescape/share/prms/runescape.prm.example"
Checking if any known files are still using the old folder structure

Checking if any default configurations are missing

Trying to read /home/dan/.config/runescape/share/configs/settings.conf
Error reading settings.conf, using default value: 0
Error reading settings.conf, using default value: default-java
Error reading settings.conf, using default value: 0
Error reading settings.conf, using default value: 0
Error reading settings.conf, using default value: runescape.prm
Error reading settings.conf, using default value: false
Error reading settings.conf, using default value: true
Error reading settings.conf, using default value: default

Checking if any --verbose parameters were passed to the script
The --verbose parameter was not passed to the script.
Java will be executed without extra output.

Locating the binary that /usr/bin/java is symlinked to.
/usr/bin/java -> /etc/alternatives/java
/etc/alternatives/java -> /usr/lib/jvm/java-6-openjdk-armhf/jre/bin/java
Java binary located: /usr/lib/jvm/java-6-openjdk-armhf/jre/bin/java

Reading .prm file /home/dan/.config/runescape/share/prms/runescape.prm
This is the info I gathered from the runescape.prm file
######## File Start ########

 -Djava.class.path=jagexappletviewer.jar
 -Dsun.java2d.noddraw=true
 -Dcom.jagex.config=http://www.runescape.com/k=3/l=$(Language:0)/jav_config.ws
 -Xmx512m
 
 -Xss2m
 
 
 
 -Xdebug
 
 jagexappletviewer

######## File End ########

I will now parse the parameters!
Error reading settings.conf, using default value: undef
Checking your client language setting(if any)
Trying to read file
/home/dan/.config/runescape/share/cache/jagexappletviewer.preferences

File read and this is the content I found!
######## File Start ########

Language=0

######## File End ########

I will now parse the contents from the
jagexappletviewer.preferences file so it can be used.
Stitching the language setting to the final parameters.

Final parameter string is:
 jagexappletviewer.jar -Dsun.java2d.noddraw=true -Dcom.jagex.config=http://www.runescape.com/k=3/l=0/jav_config.ws -Xmx512m  -Xss2m    -Xdebug  jagexappletviewer

Launching client using this java version: 
java version "1.6.0_41"
OpenJDK Runtime Environment (IcedTea6 1.13.13) (6b41-1.13.13-0ubuntu0.14.04.1)
OpenJDK Zero VM (build 23.41-b41, interpreted mode)

Fixing possible OpenGL issues by adding the environment variable
LD_LIBRARY_PATH=/opt/runescape/rsu/3rdParty/linux/cairo-nogl/i386/:/opt/runescape/rsu/3rdParty/linux/cairo-nogl/x86_64/:/usr/lib/jvm/java-6-openjdk-armhf/jre/bin/../lib/arm/:/usr/lib/jvm/java-6-openjdk-armhf/jre/bin/../lib/arm/jli/:$LD_LIBRARY_PATH

Adding optimization parameters to Java.
Parameters that will be added are:
-XX:+AggressiveOpts -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+TieredCompilation -XX:ReservedCodeCacheSize=256m -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=16 -XX:+UseParallelGC
NOTE: If any of these are added to the prm file the parameter from the prm file will be used instead!

Launching the RuneScape Client using this command:
cd /home/dan/.config/runescape/bin && LD_LIBRARY_PATH=/opt/runescape/rsu/3rdParty/linux/cairo-nogl/i386/:/opt/runescape/rsu/3rdParty/linux/cairo-nogl/x86_64/:/usr/lib/jvm/java-6-openjdk-armhf/jre/bin/../lib/arm/:/usr/lib/jvm/java-6-openjdk-armhf/jre/bin/../lib/arm/jli/:$LD_LIBRARY_PATH /usr/lib/jvm/java-6-openjdk-armhf/jre/bin/java -XX:+AggressiveOpts -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+TieredCompilation -XX:ReservedCodeCacheSize=256m -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=16 -XX:+UseParallelGC -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Duser.home="/home/dan/.config/runescape/share/cache"   -cp   jagexappletviewer.jar -Dsun.java2d.noddraw=true -Dcom.jagex.config=http://www.runescape.com/k=3/l=0/jav_config.ws -Xmx512m  -Xss2m    -Xdebug  jagexappletviewer /share/img/RuneScape3

Executing the RuneScape Client!
You are now in the hands of Jagex.

######## Jagex client output will appear below here ########

Trying to load icon file: /home/dan/.config/runescape/share/img/RuneScape3/jagexappletviewer.png
Loader init
Init 1
Init 2
Init 3
Init 4
Init 5
Init 6
Init 7
Init 8
Loader show
Loader set message
Config url:http://www.runescape.com/k=3/l=0/jav_config.ws
Config URL is http://www.runescape.com/k=3/l=0/jav_config.ws
Exception in thread "AWT-EventQueue-1" sun.java2d.InvalidPipeException: attempt to validate Pipe with invalid SurfaceData
        at sun.java2d.SunGraphics2D.validatePipe(SunGraphics2D.java:380)
        at sun.java2d.SunGraphics2D.clearRect(SunGraphics2D.java:2370)
        at java.awt.Container.update(Container.java:1803)
        at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
        at sun.awt.X11.XRepaintArea.updateComponent(XRepaintArea.java:60)
        at sun.awt.RepaintArea.paint(RepaintArea.java:232)
        at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:705)
        at java.awt.Component.dispatchEventImpl(Component.java:4725)
        at java.awt.Container.dispatchEventImpl(Container.java:2103)
        at java.awt.Window.dispatchEventImpl(Window.java:2588)
        at java.awt.Component.dispatchEvent(Component.java:4475)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:686)
        at java.awt.EventQueue.access$400(EventQueue.java:96)
        at java.awt.EventQueue$2.run(EventQueue.java:645)
        at java.awt.EventQueue$2.run(EventQueue.java:643)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$3.run(EventQueue.java:659)
        at java.awt.EventQueue$3.run(EventQueue.java:657)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:656)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:281)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
Error: client.init:1108 sun.reflect.NativeMethodAccessorImpl.invoke0 sun.reflect.NativeMethodAccessorImpl.invoke:57 sun.reflect.DelegatingMethodAccessorImpl.invoke:43 java.lang.reflect.Method.invoke:622 Rs2Applet.a:17 Rs2Applet.init:597 app.appletviewer.a:846 jagexappletviewer.main:34 | java.lang.RuntimeException | 
sun.awt.image.ImageFormatException: Unsupported color conversion request
        at sun.awt.image.JPEGImageDecoder.readImage(Native Method)
        at sun.awt.image.JPEGImageDecoder.produceImage(JPEGImageDecoder.java:136)
        at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:264)
        at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:189)
        at sun.awt.image.ImageFetcher.run(ImageFetcher.java:153)

*****************************8

The last part with the error occurs at the Loading 2% mark, at which point the loading stops.  I didn't see this problem in other issue threads, so I thought I'd try a new one.  I'd appreciate any suggestions.  Thanks!

**Comment by HikariKnight** [comment]
@smithillusions seems to be a java based issue or a jagex based issue as my script finished its thing and gave control to the appletviewer without issues

**Comment by smithillusions** [comment]
Hmm alright.  Thank you @HikariKnight for the prompt response.  I don't know if this is of any use but the command 'runescape' doesn't launch the client but instead outputs:

(trusty)dan@localhost:~$ runescape
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work

WARNING: LWP::Simple module not found, API calls using LWP::Simple will either use alternative methods

Use of uninitialized value $apicall in substitution (s///) at /opt/runescape/rsu/apiquery.pm line 43.
Use of uninitialized value $apicall in concatenation (.) or string at /opt/runescape/rsu/apiquery.pm line 46.
syntax error at (eval 45) line 1, at EOF
        ...caught at /opt/runescape/rsu/apiquery.pm line 46.

I don't know if this means there are additional things I have to install to properly run.  I'll see if I can figure anything out and post back if I do.  If you have further recommendations on how to address a java issue, please let me know.  Thanks again!

**Comment by HikariKnight** [comment]
thats an ARM issue believe it or not :p
its kinda weird
