### ISSUE TITLE
Sticks on "New game client" after logging in and I can't click the buttons

### ISSUE THREAD

**Issue by crabcrabcam** [rsu-client/rsu-client#118]
Ubuntu Mint 18.1 installed from PPA

I installed, logged in and all seemed fine (account was locked and I managed to reset it)
I also used the wrong email (very old account wasn't sure what email I used) and it made a new account and put me in game. 
Now when I log in with my real account it asks me to download the new game client but I can't click "Download" or "Remind me later". If I right click it gives me the options "Choose option" or "Cancel" but moving the mouse removes this menu. 

I've just managed to click the download button by accident. The buttons are WAY off where they appear on screen. The download button takes me to the official page to download the Windows/Mac client (Linux client buttons are there but interestingly take you to a 404. Would have thought they'd go to the FAQ page or not be there since it's not officially supported). 

I've managed to get in by finding the remind me later button's actual position. Not sure if this is something you can fix though. 

CC: @HikariKnight

**Comment by ivanpu** [comment]
1. This is Jagex's way to switch everybody from Java to NXT. And honestly I think you should, unless your computer can't run it. 
2. The Linux link for it just opens installation instructions below it - this is not a download link. 

_Sent from my LGE LG-H815 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by crabcrabcam** [comment]
@ivanpu I got a 404 on the Linux page but it's probably because of Javascript as you mention. Is there any way to get NXT for Linux, is it through here or no?

**Comment by ivanpu** [comment]
Here's the instructions, [verbatim](https://www.runescape.com/download):

> **Ubuntu Linux (amd64/x86_64 only)**
To install the launcher for Ubuntu (and other similar Debian-based distributions), you can paste the following into a console, and enter your password when prompted. This will add the RuneScape apt repository to your computer so that you will be informed of updates to the launcher when they happen.
>```
>sudo -s -- << EOF
>wget -O - https://content.runescape.com/downloads/ubuntu/runescape.gpg.key | apt-key add -
>mkdir -p /etc/apt/sources.list.d
>echo "deb https://content.runescape.com/downloads/ubuntu trusty non-free" > >/etc/apt/sources.list.d/runescape.list
>apt-get update
>apt-get install -y runescape-launcher
>EOF
>```

Should work on Mint, as it's Ubuntu derivative.

**Comment by hhyyrylainen** [comment]
I get a black screen with the NXT client and as I can't dismiss this message about the new version I can't play at all. Would be nice to have some kind of fix for this.

**Comment by HikariKnight** [comment]
hi @hhyyrylainen that is not something we can do as the game has already launched at that point, which means all the prep work the rsu-client does is done.
the issue youre having is either hardware related (intel graphics tend to not play well with anything) or a different issue which only jagex would be able to help you with

**Comment by hhyyrylainen** [comment]
Thanks for commenting. I did find a few relevant links about the nxt issue:
https://www.reddit.com/r/runescape/comments/7ab2z2/runescape_nxt_black_screen_bug_caused_from_newer/
http://services.runescape.com/m=forum/c=3IsAs6RlF4w/sl=0/forums.ws?415,416,846,65973896
http://services.runescape.com/m=forum/forums.ws?415,416,707,65950789,goto,2

Which seem to confirm that the nxt issue is with jagex being too lazy to fix their engine to work with the latest nvidia drivers. And as I can't easily downgrade my drivers, I guess I'm not playing runescape, until jagex learns to fix their stuff.

**Comment by HikariKnight** [comment]
if the issue was in the nxt client itself then yeah its entirely in jagex hands as this project is the legacy linux client essentially
