### ISSUE TITLE
Void Linux Package

### ISSUE THREAD

**Issue by ibrokemypie** [rsu-client/rsu-client#121]
I have been trying to put together a package for void linux, however I am finding the directory structure truly confusing. Any chance you could lend a hand?
https://github.com/voidlinux/void-packages/pull/6725

**Comment by HikariKnight** [comment]
Will have a look once I'm at the PC, but I know the aur repository by @ivan_p is a good example of how it is.

Places the client in /opt so it rubs from /opt/runescape
And then copies some scripts and .desktop files from the templates folder and done pretty much

I recently made a makefile for that to help bring the client to Debian

**Comment by HikariKnight** [comment]
https://github.com/HikariKnight/runescape/blob/master/Makefile

**Comment by HikariKnight** [comment]
@ibrokemypie

**Comment by HikariKnight** [comment]
ok im back home and had a read through the link you sent me

the client is made to run from anywhere to be honest
if you need to install it anywhere else then you need to edit the template scripts in
https://github.com/HikariKnight/rsu-client/tree/master/runescape/templates/packaging/usr/games
to suit your system (just add another elsif with the right path to the client in the 3 scripts)

these 3 scripts are what you should use to put in the systems designated $PATH by copying them to /usr/bin or wherever else they may store binaries.

you can also make that edit and request me to pull said changes into this branch so if you want to make an automatic script to always pull the newest version you can just copy the original templates without modifying them.

but you will have to modify the .desktop files inside
https://github.com/HikariKnight/rsu-client/tree/master/runescape/templates/packaging/usr/share/applications
as these are hardcoded to use /opt/runescape as the installed location, but it is an easy thing to replace with sed or through some other means.

as far as anything else goes i do not think anything is hardcoded to /opt in the actual framework if it detects that it is running from a location that is not inside $HOME
