### ISSUE TITLE
ERROR Loading Application

### ISSUE THREAD

**Issue by RichCmbMedic** [rsu-client/rsu-client#137]
When I go to log onto RS through the client, it loads application, gets to %98-100 then gives me an error box. It is completely black with a small box that when clicked just says 'Quit'. 
Is this a user error or something else? First time I have dealt with this issue.

**Comment by RyoshiKayo** [comment]
We need to know your OS, what version, etc before we can even attempt helping you.

**Comment by HikariKnight** [comment]
no info for months, closing, please reopen if you still need help.
