### ISSUE TITLE
Runescape not loading login portion

### ISSUE THREAD

**Issue by ghost** [rsu-client/rsu-client#140]
Ubuntu 18.04 using the Debian install method.

**Comment by soaringowl2145** [comment]
![image](https://user-images.githubusercontent.com/24739821/40127357-31a50e58-58fd-11e8-8ec4-564497a6ba81.png)

**Comment by soaringowl2145** [comment]
Old School is perfect though.

**Comment by nolifeorname** [comment]
it looks like you are on ubuntu,
there is a different install method for that distro so maybe try that one out?

**Comment by nolifeorname** [comment]
```
sudo apt-add-repository ppa:hikariknight/unix-runescape-client
sudo apt-get update && sudo apt-get install unix-runescape-client
```

**Comment by soaringowl2145** [comment]
How do I know that my download has not been tampered with when using a PPA?

**Comment by soaringowl2145** [comment]
Also that still did not fix it.

**Comment by nolifeorname** [comment]
in the debian method you are doing basically the same by configuring an external repo

**Comment by nolifeorname** [comment]
have you tried clearing your jagex cache (should be in your home directory)

**Comment by nolifeorname** [comment]
also if that doesn't work: HikariKnight has a forum post with linux support for runescape ( http://services.runescape.com/m=forum/forums.ws?409,410,916,65990459 )
where he explains how to use 32bit java on a 64bit system

> ~ Using 32bit Java on a 64bit Linux system ~
> Make sure you have the 32bit libraries installed, follow the steps for your system below.
> 
> Debian:
> su
> apt-get install ia32-libs
> 
> Ubuntu(and other *ubuntu versions) and LinuxMint(or similar forks of ubuntu):
> sudo apt-get install ia32-libs
> 
> Fedora:
> N/A - please provide command
> 
> Suse/OpenSuse:
> N/A - please provide command
> 
> ArchLinux:
> Follow the instructions on the ArchLinux wiki
> https://wiki.archlinux.or­g/index.php/Multilib
> 
> then run "pacman -Syy" in the Terminal to refresh the packages database

**Comment by nolifeorname** [comment]
also this might be it:

> There's a command you have to use on Ubuntu to install NXT, that basically involves downloading an older version of a specific library, and it comes up about 4 times per page on the old thread. I'll dig it out quick!
> 
> EDIT: BINGO!
> 
> Original message details are unavailable.
> 
> sudo wget http://launchpadlibrarian.net/161405671/libglew1.10_1.10.0-3_amd64.deb
> sudo dpkg -i libglew1.10_1.10.0-3_amd64.deb
> 
> Seems to be because Nxt is built upon such an ancient version of Ubuntu, it won't run on newer versions without this.

**Comment by HikariKnight** [comment]
failing to render the login portion is an odd issue i see rarely, i would recommend clearing the jagexcache as that is what could cause issues like this. sadly i have no other solution you can try for it as its not an issue i have ever faced myself, i just know that a corrupt cache can cause lots of interesting and odd issues.

**Comment by SmOkEwOw** [comment]
I have the same issue, installing 32 bit java doesn't work (package not found), unix-runescape-launcher (package not found, probably not avaible in ubuntu 18 yet), NXT launcher doesn't work too, it not even opens. RSU client is the only that opens the game, but there's no login box, also the auto-setup box doesn't popup too, i can't open settings too.

Here is the console logs: https://pastebin.com/w25NgUeu
