### ISSUE TITLE
Unable to locate Package unix-runescape-client

### ISSUE THREAD

**Issue by trilerium** [rsu-client/rsu-client#143]
@HikariKnight 
Apologies in advance, I'm a novice linux user who has played around with Ubuntu and Mint since 2012 but never used it as my main OS for more than 4 months at a time. I tried installing the URC on my machine running Ubuntu 18.04 using

`sudo apt-add-repository ppa:hikariknight/unix-runescape-client`

followed by

`sudo apt-get update && sudo apt-get install unix-runescape-client`

and received the error 

`E: Unable to locate package unix-runescape-client`

I'm not sure what I could be doing wrong. I should also say that this is a fresh install of Ubuntu 18.04. is there something I'm missing?

**Comment by trilerium** [comment]
Not sure why but I seem to have been able to install it buy using 
`Sudo apt-get install runescape`

**Comment by RyoshiKayo** [comment]
In general if you don't know what a package name is you can do `sudo apt seach runescape`
