### ISSUE TITLE
Starting fresh on ubuntu, can't use desktop temporarily, osrs not working

### ISSUE THREAD

**Issue by EternalSlushy** [rsu-client/rsu-client#149]
This here is the file I've download because I believe I have x64 system...
![first uploadxxx999](https://user-images.githubusercontent.com/43737039/46269715-bd7f4180-c4f7-11e8-90d9-363afeb916bd.jpg)
This is the error I get before it finished installing...
![2nd upload09jj90](https://user-images.githubusercontent.com/43737039/46269737-d687f280-c4f7-11e8-9207-859bd178ccda.jpg)
And this is what is inside of the folder it creates - theres only 3 files all for uninstalling it. Where's the launcher?
![3rd uploadxx99](https://user-images.githubusercontent.com/43737039/46269750-ebfd1c80-c4f7-11e8-979c-848cfc967925.jpg)

**Comment by RyoshiKayo** [comment]
Ubuntu has a screenshot utility...

Without seeing any logs my best guess is that the launcher wasn't able to download a perl module.

**Comment by abacefbeca** [comment]
You're using Ubuntu. Is there a reason you didn't use the PPA which makes it much easier to install the RSU client launcher? Open a Terminal window and do

`sudo apt-add-repository ppa:hikariknight/unix-runescape-client`

After that is done type in the following 

`sudo apt-get update && sudo apt-get install unix-runescape-client`

Currently there seems to be an issue with the installers like the one you downloaded. The Windows installer doesn't work, either.

**Comment by abacefbeca** [comment]
@HikariKnight 

Are there any plans to fix the installers?

**Comment by HikariKnight** [comment]
i will have to update and rebuild the installers, i will look into that, as they stop working when there are major updates in the bitrock installer framework involving the download code
cheers for tag @abacefbeca

**Comment by HikariKnight** [comment]
@abacefbeca installers are now fixed, whew the installer builder have had 10 major updates since last buildl :sweat_smile:

**Comment by HikariKnight** [comment]
@EternalSlushy the installers should work now when you redownload them :)
