### ISSUE TITLE
Flickering at menu. Stuck

### ISSUE THREAD

**Issue by Suzner** [rsu-client/rsu-client#150]
@hikariknight after downloading everything... I can run osrs totally fine. But when I try to launch rs3. It starts, updates, then sits on the menu screen and flickers endlessly. Any idea why it won't start?

I use a chromebook, with Linux vm.

Thanks!

**Comment by Suzner** [comment]
If all else fails I can always just ply osrs, but my acct is on rs3. hopefully @HikariKnight can help us!!

**Comment by RyoshiKayo** [comment]
Same issue as #133
