### ISSUE TITLE
not work on xp?

### ISSUE THREAD

**Issue by hasproblem** [rsu-client/rsu-client#154]
a loading bar just appears, loads some things, goes away and nothing else happens, I tried with no java, java 7 and java 8

**Comment by hasproblem** [comment]
I was thinking of starting os.  And rs3 runs just fine on xp for me, you just need the older client. http://www.runescape.com/downloads/runescape.msi

**Comment by hasproblem** [comment]
I was thinking os. And the older rs3 client still works on xp, I think it's actually better. Download is still available on rs homepage http://www.runescape.com/downloads/runescape.msi, even the rs classic client is still available http://www.runescape.com/downloads/runescape.exe

**Comment by HikariKnight** [comment]
to follow up on this, the official legacy clients use openjdk6 (if i remember correctly) and bundle it with the client hence why they still work on windows
