### ISSUE TITLE
Could not find or load main class jagexappletviewer

### ISSUE THREAD

**Issue by annadane** [rsu-client/rsu-client#156]
annadane@debian:~$ ./rsu-client-master/runescape/runescape
touch: cannot touch '/home/annadane/.local/share/applications/mimeapps.list': No such file or directory
/usr/bin/xdg-mime: 803: /usr/bin/xdg-mime: cannot create /home/annadane/.local/share/applications/mimeapps.list.new: Directory nonexistent
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
WARNING: Wx module not found, API calls using WxWidgets will not work

WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work

WARNING: List::MoreUtils module not found on the system,
using the version provided by the client instead!

WARNING: IO::Stringy module not found on the system,
using the version provided by the client instead!

WARNING: Config::IniFiles module not found on the system,
using the version provided by the client instead!

RuneScape Unix Client script version 4.3.7

touch: cannot touch '/home/annadane/.local/share/applications/mimeapps.list': No such file or directory
/usr/bin/xdg-mime: 803: /usr/bin/xdg-mime: cannot create /home/annadane/.local/share/applications/mimeapps.list.new: Directory nonexistent
WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
WARNING: Wx module not found, API calls using WxWidgets will not work

WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work

WARNING: List::MoreUtils module not found on the system,
using the version provided by the client instead!

WARNING: IO::Stringy module not found on the system,
using the version provided by the client instead!

WARNING: Config::IniFiles module not found on the system,
using the version provided by the client instead!

--2018-11-12 11:29:39--  https://www.runescape.com/downloads/oldschool.msi
Resolving www.runescape.com (www.runescape.com)... 91.235.140.148
Connecting to www.runescape.com (www.runescape.com)|91.235.140.148|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24018944 (23M) [application/octet-stream]
Saving to: ‘/home/annadane/rsu-client-master/runescape/.download/oldschool.msi’

/home/annadane/rsu-client-master/runesc 100%[=============================================================================>]  22.91M  4.16MB/s    in 5.8s    

2018-11-12 11:29:46 (3.98 MB/s) - ‘/home/annadane/rsu-client-master/runescape/.download/oldschool.msi’ saved [24018944/24018944]

sh: 1: 7z: not found
readdir() attempted on invalid dirhandle $dir_content at /home/annadane/rsu-client-master/runescape/rsu/framework/modules/rsu/files/dirs.pm line 47.
Trying to read /home/annadane/rsu-client-master/runescape/share/configs/settings.conf
Reading value from "compabilitymode"
Setting script data compabilitymode to false
Reading value from "preferredjava"
Setting script data preferredjava to default-java
Reading value from "forcepulseaudio"
Setting script data forcepulseaudio to false
Reading value from "forcealsa"
Setting script data forcealsa to false
Reading value from "prmfile"
Setting script data prmfile to runescape.prm
Reading value from "useprimusrun"
Setting script data useprimusrun to false
Reading value from "optimizejava"
Setting script data optimizejava to true
Reading value from "cachedir"
Setting script data cachedir to default

Checking if any --verbose parameters were passed to the script
The --verbose parameter was not passed to the script.
Java will be executed without extra output.

Locating the binary that /usr/bin/java is symlinked to.
/usr/bin/java -> /etc/alternatives/java
/etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
Java binary located: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

Reading .prm file /home/annadane/rsu-client-master/runescape/share/prms/runescape.prm
This is the info I gathered from the runescape.prm file
######## File Start ########
-Djava.class.path=jagexappletviewer.jar
 -Dcom.jagex.config=http://www.runescape.com/k=3/l=$(Language:0)/jav_config.ws
 -Xmx512m
 -Xss2m
 -Dsun.java2d.noddraw=true
 jagexappletviewer

######## File End ########

I will now parse the parameters!
Checking your client language setting(if any)
Trying to read file
/home/annadane/rsu-client-master/runescape/share/cache/jagexappletviewer.preferences

Unable to read jagexappletviewer.preferences file, defaulting to Language=0 (English).
I will now parse the contents from the
jagexappletviewer.preferences file so it can be used.
Stitching the language setting to the final parameters.

Final parameter string is:
jagexappletviewer.jar -Dcom.jagex.config=http://www.runescape.com/k=3/l=0/jav_config.ws -Xmx512m -Xss2m -Dsun.java2d.noddraw=true jagexappletviewer

Launching client using this java version: 
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

Fixing possible OpenGL issues by adding the environment variable
LD_LIBRARY_PATH=/home/annadane/rsu-client-master/runescape/rsu/3rdParty/linux/cairo-nogl/i386/:/home/annadane/rsu-client-master/runescape/rsu/3rdParty/linux/cairo-nogl/x86_64/:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/../lib/amd64/:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/../lib/amd64/jli/:$LD_LIBRARY_PATH

Adding optimization parameters to Java.
Parameters that will be added are:
-XX:+AggressiveOpts -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+TieredCompilation -XX:ReservedCodeCacheSize=256m -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=16 -XX:+UseParallelGC
NOTE: If any of these are added to the prm file the parameter from the prm file will be used instead!

Launching the RuneScape Client using this command:
cd /home/annadane/rsu-client-master/runescape/bin && LD_LIBRARY_PATH=/home/annadane/rsu-client-master/runescape/rsu/3rdParty/linux/cairo-nogl/i386/:/home/annadane/rsu-client-master/runescape/rsu/3rdParty/linux/cairo-nogl/x86_64/:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/../lib/amd64/:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/../lib/amd64/jli/:$LD_LIBRARY_PATH /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -XX:+AggressiveOpts -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+TieredCompilation -XX:ReservedCodeCacheSize=256m -XX:+UseAdaptiveGCBoundary -XX:SurvivorRatio=16 -XX:+UseParallelGC -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Duser.home="/home/annadane/rsu-client-master/runescape/share/cache"   -cp  jagexappletviewer.jar -Dcom.jagex.config=http://www.runescape.com/k=3/l=0/jav_config.ws -Xmx512m -Xss2m -Dsun.java2d.noddraw=true jagexappletviewer /share/img/RuneScape3

Executing the RuneScape Client!
You are now in the hands of Jagex.

######## Jagex client output will appear below here ########

Error: Could not find or load main class jagexappletviewer

**Comment by abacefbeca** [comment]
@HikariKnight Do I have that correct?
