### ISSUE TITLE
Script breaks xdg-open on Linux

### ISSUE THREAD

**Issue by duelistone** [rsu-client/rsu-client#157]
I noticed that a script by @HikariKnight and others meant as a wrapper to xdg-open breaks xdg-open for files with spaces in their name. The culprit is the following line in /usr/local/bin/xdg-open (on Debian):

`env "$tempdir/xdg-open" $@`

This should instead be

`env "$tempdir/xdg-open" "$@"`

so that the command line arguments are passed on to the real xdg-open correctly. This fixed the issue in my installation, but I'm posting this here anyways in case it happens to someone else.

**Comment by HikariKnight** [comment]
i will fix that right away
