### ISSUE TITLE
just stopped working

### ISSUE THREAD

**Issue by hasproblem** [rsu-client/rsu-client#159]
Installed a pdf reader, now doesn't work, probably not related. 

This error:

Reading value from "newschannel"
Setting script data newschannel to runescape
Fetching the current playercount.
** GET http://www.runescape.com/player_count.js?varname=iPlayerCount&callback=jQ
uery17209493430445436388_1382425275438&_=1552346321 ==> 200 OK
Fetching the current playercount from Old School RuneScape.
Reading value from "prmfile"
Setting script data prmfile to runescape.prm

Response from RSSFEED: IO::Socket::SSL 1.42 must be installed for https support

This is the RSS contents we found:
IO::Socket::SSL 1.42 must be installed for https support

Content must be RSS|RDF|ScriptingNews|Weblog|reasonably close at C:/Users/Admini
strator/runescape/rsu/framework/Perl5lib/XML/RSSLite.pm line 32.
Compilation failed in require at (eval 60) line 2.
BEGIN failed--compilation aborted at (eval 60) line 2.
        ...caught at C:/Users/Administrator/runescape/rsu/apiquery.pm line 46.

C:\Users\Administrator\runescape\rsu>

**Comment by JacobSvenningsen** [comment]
#155 This pull-request also contains a fix for that. Apparently the client tries connecting to the news using http rather than https.
You could try replacing rsu/framework/API/client/launch/launcher.pm with the version from that pull-request, see if that helps

**Comment by hasproblem** [comment]
ty, works now

**Comment by HikariKnight** [comment]
Fixed with patch from @JacobSvenningsen pull request
