### ISSUE TITLE
4k monitor icon scaling

### ISSUE THREAD

**Issue by kdbeall** [rsu-client/rsu-client#161]
@HikariKnight First, thank you so much for all the hard work you've put into this!

I'm running Ubuntu 18.04 and have a 4k monitor. 
When I play Old School Runescape, the icons are incredibly small.
I would like the icons to be scaled 200% (as with the rest of my icons).

![Screenshot from 2019-03-30 19-11-29](https://user-images.githubusercontent.com/10102694/55282684-ab078880-531f-11e9-933b-364747ad6864.png)

**Comment by RyoshiKayo** [comment]
This project cannot help you with the UI scale. You should be able to scale it within the game settings, I found this from Googling: https://oldschoolrunescape.fandom.com/wiki/Update:Resizable_Mode

**Comment by kdbeall** [comment]
@RyoshiKayo I've already enabled resizable mode, and that didn't fix the issue. 

Adding this environmental variable fixes the issue. 

     export GDK_SCALE=2

Is there a way I can add this to the configuration file?

**Comment by HikariKnight** [comment]
hi @kdbeall you should if i remember correctly be able to add it by adding
```
env GDK_SCALE=2
```
in front of the launch command in the .desktop file for the client, pretty sure i coded it in to take environment variables passed to it and forward them to the actual launch command.

should look like
```
env GDK_SCALE=2 runescape
```
or
```
env GDK_SCALE=2 rsu-query client.launch.runescape
```

you may or may not have to pass --prmfile=oldschool.prm to the command too
