### ISSUE TITLE
Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

### ISSUE THREAD

**Issue by and31** [rsu-client/rsu-client#166]
I am getting this error message after trying to open the client.
I downloaded from the apt repository, launched the RSU Launcher and clicked "Play Now". RS3 client opens, starts updating and music plays successfully. All of a sudden the game closes and I get this message on the console:

> Inconsistency detected by ld.so: dl-lookup.c: 112: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

I thought it could have been related with a debug flag in the settings and removed it, but it did not fix the issue.
Any troubleshooting tips?
@HikariKnight

**Comment by HikariKnight** [comment]
if the game window opened then all the tasks from my script is done, but just incase provide the terminal output of the launcher, you can run it with either
```
runescape
```
or
```
runescape client.launch.runescape
```

but i doubt that error is related to my launcher since i do not use C, but Perl
that and since the RS window opened it means it found java and linked the appropriate openGL libraries and fixed audio (hopefully) if there was any audio problems, at which point my scripts are done :thinking:

**Comment by and31** [comment]
You seem to be correct @HikariKnight it is after your script is done. Here is the output of the debug if you (or anyone else for that matter) would kindly help me troubleshoot.
https://pastebin.com/RgVbZZdp

**Comment by HikariKnight** [comment]
ok @and31 only thing i can think of trying is to disable the cairo-nogl library which is there for compatibility with older hardware (and i have no proper way to detect if its needed or not)

```
sudo mv /opt/runescape/rsu/3rdParty/linux/cairo-nogl /opt/runescape/rsu/3rdParty/linux/cairo-nogl.disabled
```

that is the only thing i can think of that could trigger ld.so inconsistency as it is a very old .so library file

**Comment by HikariKnight** [comment]
Also another thing to note is that, try use openjdk-8, i know newer java versions can cause issues for runescape and even minecraft

**Comment by and31** [comment]
@HikariKnight changing to run with onejdk-7 allowed the client to load the client completely and I was able to log in. Thanks for the help.

**Comment by HikariKnight** [comment]
youre welcome, just keep in mind that anything newer than java 8 can be problematic so i would recommend backing up openjdk-8 or 7 or get the oracle java7 or 8 if you can and just manually tell the client to use that java binary in the future ;)
