### ISSUE TITLE
Error executing the launcher

### ISSUE THREAD

**Issue by MrDrago** [rsu-client/rsu-client#168]
**When executing the launcher for linux this error occurs:**

`Can't locate Archive/Extract.pm in @INC (you may need to install the Archive::Extract module) (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base .) at /home/elvaquero/runescape/rsu/rsu-query line 11.
BEGIN failed--compilation aborted at /home/elvaquero/runescape/rsu/rsu-query line 11.
`

**When trying to run the version for Wine this happens:**

`fixme:ver:GetCurrentPackageId (0x8ff6fc (nil)): stub
fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_CONNECTED_STATE: STUB
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:secur32:schannel_get_protocol unknown protocol 5
fixme:secur32:schannel_get_cipher_algid unknown algorithm 10
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_kx_algid unknown algorithm 12
fixme:secur32:schannel_get_cipher_block_size Unknown cipher 0xa, returning 1
fixme:secur32:schannel_get_protocol unknown protocol 5
fixme:secur32:schannel_get_cipher_algid unknown algorithm 10
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_kx_algid unknown algorithm 12
GnuTLS error: A TLS fatal alert has been received.
err:secur32:schan_DecryptMessage Returning 80090304
fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_CONNECTED_STATE: STUB
fixme:secur32:schannel_get_protocol unknown protocol 5
fixme:secur32:schannel_get_cipher_algid unknown algorithm 10
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_kx_algid unknown algorithm 12
fixme:secur32:schannel_get_cipher_block_size Unknown cipher 0xa, returning 1
fixme:secur32:schannel_get_protocol unknown protocol 5
fixme:secur32:schannel_get_cipher_algid unknown algorithm 10
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_kx_algid unknown algorithm 12
GnuTLS error: A TLS fatal alert has been received.
err:secur32:schan_DecryptMessage Returning 80090304
fixme:wininet:InternetSetOptionW Option INTERNET_OPTION_CONNECTED_STATE: STUB
fixme:win:LockWindowUpdate ((nil)), partial stub!
`

What could be happening?

Currently my S.O is ubuntu

**Comment by HikariKnight** [comment]
@MrDrago  "you may need to install the Archive::Extract module"
if you installed the client through the PPA you would already have it installed
`sudo apt install libarchive-extract-perl`
