### ISSUE TITLE
A problem has occurred while running the game.

### ISSUE THREAD

**Issue by MaximusLuciu** [rsu-client/rsu-client#172]
I can always log in without too many problems, but during the game randomly the following error appears :
A problem has occurred while running the game.

This game has encountered a problem and cannot continue running.

We strive for our games to work on as many computers as possible and to be free of bugs.

If you are able to reproduce this problem (i.e. it always occurs when you do a certain thing), then please submit a bug report via our website, and we will try to fix it as soon as possible.

If problems persist, please refer to the Technical FAQs, which can be found in the Customer Support section of our website.
I already tried several corrections but none helped

**Comment by HikariKnight** [comment]
This is an issue related to the game itself.
best you can do is launch it through the terminal and see what the error output is.

stack out of bounds = increase stack size
memory out of bounds (or similar) = increase memory

you find both of this in settings. if neither works its a jagex issue as this happens after the client has started
