### ISSUE TITLE
doesn't work on windows for 1 year now

### ISSUE THREAD

**Issue by puddingepoch** [rsu-client/rsu-client#173]
this client has not worked on windows for over a year
i can understand you ignoring pleas for help about bsd and similar platforms but this client touts official windows support

can we please get this fixed...?

**Comment by puddingepoch** [comment]
hello

**Comment by puddingepoch** [comment]
remove the claims of suipport for windows, bsd, solaris etc 
its never worked on there and you ignore all qeuries relating to it

**Comment by puddingepoch** [comment]
you are as useless and unreliable as jagex themselves

**Comment by RyoshiKayo** [comment]
If you want to run on windows I would recommend downloading the official client from Jagex...

...as they support windows.
