### ISSUE TITLE
this no longer works for rs3

### ISSUE THREAD

**Issue by hoo694** [rsu-client/rsu-client#174]
@HikariKnight 

it is no longer possible to use rs3 to connect rs3 servers, i simply am told "support for the java client has been dropped"

now, it appears as if its stilll able to grab all the necessary .jar files and libraries to run, so i think that this could be bypassed somehow?

**Comment by HikariKnight** [comment]
hi @hoo694 use openjdk8 instead of openjdk13
runescape does not work on anything newer than java8 from my knowledge

**Comment by hoo694** [comment]
And this would once again enable the rsu-client to connect to the RS3 servers? because when I try, it says that java client is no longer supported.

**Comment by HikariKnight** [comment]
ah ok i see they have actually removed support for the java client now.
i cant really do anything about that sadly and the NXT client is very limited to what can be done with it without breaking the TOC.
the java client let you manipulate java itself which is how i managed to do all the tweaks i had done to the client.
